version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-Remindr}
      POSTGRES_USER: ${DB_USER:-Remindr}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Remindr}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Remindr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Remindr"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - Remindr-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://Remindr:Remindr@db:5432/Remindr
      REDIS_URL: redis://redis:6379
      SERVER_PORT: 3000
    networks:
      - Remindr-network

volumes:
  postgres_data:

networks:
  Remindr-network:
    driver: bridge